In [1]:
import numpy as np

In [7]:
# 1. numpy.linspace
# the first number is the starting no, the second no is the end point while the last no is the specified amount
# example
np.linspace(5,20,10)


array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [10]:
# 2. np.insert function insert values along the given axis before the given indices.
a = np.array([[1, 1], [2, 2], [3, 3]])
a
np.insert(a, 1, 5)
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [9]:
# 3. numpy.repeat
#The numpy.repeat function repeats the elements of an array.
#The number of repetitions is specified by the second argument repeats.
# repeat 10 5times
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [12]:
# 4. numpy.random
# The numpy.random.randint function returns random integers from the interval.
np.random.randint(3,size =10)

array([1, 0, 2, 1, 0, 0, 2, 0, 0, 1])

In [4]:
# 5. np.max is a function to get the maximum value in an array
arr = np.array((23,21,55,67,78))
arr.max()

78

In [54]:
# 6. np.transpose function reverses or permutes the axes of an ndarray.
nd1 = np.array([[1,2,3],[4,5,6]])

print(nd1)
print(np.transpose(nd1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [53]:
# 7. np.sum function sums the elements of an array over a given axis.
wet = np.array([[1,2,3],[4,5,6], [6,8,9]])
print(np.sum(wet))
print(np.sum(wet, 0))
print(np.sum(wet, 1))

44
[11 15 18]
[ 6 15 23]


In [46]:
# 8. np.reshape function rearranges the data in an ndarray into a new shape.
#The new shape must be compatible with the old one, though an index of -1 can be used to infer one dimension.

na1 = np.array([[1,2,3],[4,5,6]])

print(na1)
print(np.reshape(na1,(3,2)))
print(np.reshape(na1,(-1,1)))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [43]:
# 9. nd.log:log returns an ndarray with each element as the natural logarithm of the corresponding element in array
nd = np.array([[1,2.71828],[2.71828,1]])

print(nd)
print(np.log(nd))

[[1.      2.71828]
 [2.71828 1.     ]]
[[0.         0.99999933]
 [0.99999933 0.        ]]


In [42]:
# 10. np.append: append values to the end of an array, see insert and delete
np1 = np.array([[1,2,3],[4,5,6]])
np2 = np.array([[7,8,9],[12,13,14]])

#print(np1)
#print(np2)
print(np.append(np1,np2,0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [12 13 14]]


In [6]:
# 11. np.split Split an array into multiple sub-arrays of equal or near-equal size.
#Does not raise an exception if an equal division cannot be made.


i = np.arange(9.0)
np.split(i, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [1]:
import numpy as np
# 12.
array = np.array((10,2,3,7,18,22))
array.argmax()

5

In [12]:
# 13. numpy.tile Construct an array by repeating A the number of times given by reps.
u= np.array([0, 1, 2])
np.tile(u, 4)


array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [13]:
# 14. np.umique Find the unique elements of an array.Returns the sorted unique elements of an array. 
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [14]:
# 15. np.union1d Find the union of two arrays.
#Return the unique, sorted array of values that are in either of the two input arrays
np.union1d([-1, 0, 1], [-2, 0, 2])

array([-2, -1,  0,  1,  2])

In [15]:
# 16. np.isin Calculates element in test_elements, broadcasting over element only. Returns a boolean array of the same 
#shape as element that is True where an element of element is in test_elements and False otherwise.
element = 2*np.arange(4).reshape((2, 2))
element

array([[0, 2],
       [4, 6]])

In [17]:
# 17. np.polynomial Polynomials in NumPy can be created, manipulated, and even fitted
#using the convenience classes of the numpy.

p1 = np.polynomial.Polynomial([1, 2, 3])
p1
p2 = np.polynomial.Polynomial([1, 2, 3], domain=[-2, 2])
p1 == p2

False

In [18]:
# 18. np.who Print the NumPy arrays in the given dictionary.If there is no dictionary passed in or vardict is None then returns
#NumPy arrays in the globals() dictionary (all NumPy arrays in the namespace).
a = np.arange(10)
b = np.ones(20)
np.who()

Name               Shape            Bytes            Type

___                2 x 2            16               int32
array              6                24               int32
arr                5                20               int32
i                  9                72               float64
a                  10               40               int32
_8                 3 x 2            24               int32
_9                 7                28               int32
_10                3 x 3            36               int32
u                  3                12               int32
_11                6                24               int32
_12                12               48               int32
_13                3                12               int32
_14                5                20               int32
element (___)      2 x 2            16               int32
_15 (___)          2 x 2            16               int32
b                  20               160              f

In [22]:
# 19. np.nonzero Return the indices of the elements that are non-zero.Returns a tuple of arrays, one for each dimension of a, 
#containing the indices of the non-zero elements in that dimension. The values in a are always tested and returned in 
#row-major, C-style order.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [23]:
# 20. np.partition Creates a copy of the array with its elements rearranged in such a way that the value of the element in
#k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before 
#this element and all equal or greater are moved behind it. 
#The ordering of the elements in the two partitions is undefined.
a = np.array([3, 4, 2, 1])
np.partition(a, 3)

array([2, 1, 3, 4])